

spring:
  datasource:
    url: jdbc:mysql://rooftop-db.cjiyy4ooopv4.ap-northeast-2.rds.amazonaws.com:3306/rooftop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 12345678

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true



springdoc:
  paths-to-match:
    - /**






